from openai import OpenAI
client = OpenAI()
import json 

def get_horoscope(sign):
    print(f"Getting horoscope for {sign}")
    return f"{sign}: Next Tuesday you will befriend a baby otter."


class Agent:
    def __init__(self):
        self.tools = [{
            "type": "function",
            "name": "get_horoscope",
            "description": "Get today's horoscope for an astrological sign.",
            "parameters": {
                "type": "object",
                "properties": {
                    "sign": {
                        "type": "string",
                        "description": "An astrological sign like Taurus or Aquarius",
                    },
                },
                "required": ["sign"],
            },
        }] # tools to use
        self.name = "Agent"
        self.system_prompt = f"""
        You are a helpful oracle.
        You can use the following tools:
        {self.tools}
        """
        self.memory = [
            {"role": "system", "content": self.system_prompt}
            
        ] # memory to use
        
        
    def prompt(self, prompt):
        self.memory.append({"role": "user", "content": prompt})
        response = client.responses.create(
            model="gpt-5.1",
            tools=self.tools,
            input=self.memory
        )
        
        self.handle_tool_call(response.output)
        return response.output_text
        
    def handle_tool_call(self, output):
        
        self.memory += output
        
        for item in output:
            print(item)
            if item.type == "function_call":
                if item.name == "get_horoscope":
                    # 3. Execute the function logic for get_horoscope
                    horoscope = get_horoscope(json.loads(item.arguments))
                    
                    # 4. Provide function call results to the model
                    self.memory.append({
                        "type": "function_call_output",
                        "call_id": item.call_id,
                        "output": json.dumps({
                            "horoscope": horoscope
                        })
                    })
            elif item.type == "text":
                self.memory.append({"role": "assistant", "content": item.content})
        print(self.memory)
        response = client.responses.create(
            model="gpt-5.1",
            instructions="Respond only with a horoscope generated by a tool.",
            tools=self.tools,
            input=self.memory,
        )
    
    def run(self, user_input):
        print(self.prompt(self.system_prompt + "\n" + user_input))
        

agent = Agent()
agent.run("I'm an Aquarius. What's my horoscope?")